version: '3.8'

services:
  # ChromaDB service
  chromadb:
    image: chromadb/chroma:latest
    container_name: rag-chromadb
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    networks:
      - rag-network
    restart: unless-stopped

  # Main RAG application
  rag-app:
    build: .
    container_name: rag-app
    ports:
      - "8000:8000"
    volumes:
      - app_data:/app/data
      - chroma_local:/app/chroma_db
      - ./uploads:/app/uploads
    environment:
      # ChromaDB connection
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      
      # API Keys (set these in .env file)
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      
      # Model configuration
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-models/embedding-001}
      - LLM_for_chat=${LLM_for_chat:-openai/gpt-oss-120b}
      
      # Application settings
      - ANONYMIZED_TELEMETRY=False
    depends_on:
      - chromadb
    networks:
      - rag-network
    restart: unless-stopped

volumes:
  chroma_data:
  chroma_local:
  app_data:

networks:
  rag-network:
    driver: bridge
